const defaultHeroes = [
  {
    "type": "Keeper of the Grove",
    "id": "Ekee",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "22",
    "armor": "1",
    "life": "150",
    "regenLife": "0.8",
    "mana": "110",
    "regenMana": "1",
    "moveSpeed": "320",
    "baseAgi": "19",
    "baseInt": "24",
    "baseStr": "18",
    "bonusAgi": "1.8",
    "bonusInt": "2.8",
    "name": "Cenarius",
    "story": "",
    "bonusStr": "1.9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNKeeperOfTheGrove.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Priestess of the Moon",
    "id": "Emoo",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "12",
    "armor": "1",
    "life": "175",
    "regenLife": "1.2",
    "mana": "100",
    "regenMana": "0.8",
    "moveSpeed": "310",
    "baseAgi": "22",
    "baseInt": "16",
    "baseStr": "16",
    "bonusAgi": "2.4",
    "bonusInt": "2.6",
    "name": "Tyrande",
    "story": "",
    "bonusStr": "1.5",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNShandris.blp",
    "attackRate": "1.65",
    "attackRange": "600"
  },
  {
    "type": "Demon Hunter",
    "id": "Edem",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "18",
    "armor": "2",
    "life": "175",
    "regenLife": "1.6",
    "mana": "85",
    "regenMana": "0.8",
    "moveSpeed": "305",
    "baseAgi": "24",
    "baseInt": "16",
    "baseStr": "19",
    "bonusAgi": "2.8",
    "bonusInt": "1.9",
    "name": "Shadowfury",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroDemonHunter.blp",
    "attackRate": "1.6",
    "attackRange": "100"
  },
  {
    "type": "Warden",
    "id": "Ewar",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "25",
    "armor": "3",
    "life": "180",
    "regenLife": "1.8",
    "mana": "75",
    "regenMana": "1",
    "moveSpeed": "295",
    "baseAgi": "22",
    "baseInt": "15",
    "baseStr": "20",
    "bonusAgi": "2.4",
    "bonusInt": "1.8",
    "name": "Maiev",
    "story": "",
    "bonusStr": "2.2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroWarden.blp",
    "attackRate": "1.7",
    "attackRange": "100"
  },
  {
    "type": "Paladin",
    "id": "Hpal",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "10",
    "armor": "4",
    "life": "190",
    "regenLife": "2",
    "mana": "80",
    "regenMana": "1",
    "moveSpeed": "285",
    "baseAgi": "14",
    "baseInt": "18",
    "baseStr": "22",
    "bonusAgi": "1.5",
    "bonusInt": "1.9",
    "name": "Uther",
    "story": "",
    "bonusStr": "2.7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp",
    "attackRate": "1.7",
    "attackRange": "100"
  },
  {
    "type": "Archmage",
    "id": "Hamg",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "16",
    "armor": "1",
    "life": "150",
    "regenLife": "0.8",
    "mana": "110",
    "regenMana": "1.3",
    "moveSpeed": "315",
    "baseAgi": "17",
    "baseInt": "19",
    "baseStr": "14",
    "bonusAgi": "1",
    "bonusInt": "3.2",
    "name": "Andromath",
    "story": "",
    "bonusStr": "1.8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroArchMage.blp",
    "attackRate": "1.65",
    "attackRange": "600"
  },
  {
    "type": "Mountain King",
    "id": "Hmkg",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "15",
    "armor": "4",
    "life": "200",
    "regenLife": "1.5",
    "mana": "85",
    "regenMana": "0.9",
    "moveSpeed": "290",
    "baseAgi": "12",
    "baseInt": "15",
    "baseStr": "24",
    "bonusAgi": "1.5",
    "bonusInt": "1.5",
    "name": "Kaz Modan",
    "story": "",
    "bonusStr": "3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroMountainKing.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Blood Mage",
    "id": "Hblm",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "25",
    "armor": "2",
    "life": "150",
    "regenLife": "1.2",
    "mana": "100",
    "regenMana": "1.1",
    "moveSpeed": "290",
    "baseAgi": "16",
    "baseInt": "20",
    "baseStr": "18",
    "bonusAgi": "1.2",
    "bonusInt": "3",
    "name": "Kael",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroBloodElfPrince.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Blademaster",
    "id": "Obla",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "30",
    "armor": "3",
    "life": "175",
    "regenLife": "2",
    "mana": "95",
    "regenMana": "1.1",
    "moveSpeed": "305",
    "baseAgi": "24",
    "baseInt": "16",
    "baseStr": "19",
    "bonusAgi": "3.1",
    "bonusInt": "2",
    "name": "Samuro",
    "story": "",
    "bonusStr": "2.2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroBlademaster.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Far Seer",
    "id": "Ofar",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "12",
    "armor": "3",
    "life": "160",
    "regenLife": "1.1",
    "mana": "120",
    "regenMana": "1.2",
    "moveSpeed": "310",
    "baseAgi": "19",
    "baseInt": "23",
    "baseStr": "15",
    "bonusAgi": "1.3",
    "bonusInt": "2.9",
    "name": "Thrall",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroFarseer.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Tauren Chieftain",
    "id": "Otch",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "20",
    "armor": "0",
    "life": "220",
    "regenLife": "2.5",
    "mana": "110",
    "regenMana": "0.75",
    "moveSpeed": "285",
    "baseAgi": "10",
    "baseInt": "14",
    "baseStr": "25",
    "bonusAgi": "1.5",
    "bonusInt": "1.3",
    "name": "Cairne Dusthoof",
    "story": "",
    "bonusStr": "3.2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroTaurenChieftain.blp",
    "attackRate": "1.7",
    "attackRange": "128"
  },
  {
    "type": "Juggernault",
    "id": "Nbbc",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "15",
    "armor": "4",
    "life": "170",
    "regenLife": "1.7",
    "mana": "85",
    "regenMana": "1",
    "moveSpeed": "310",
    "baseAgi": "23",
    "baseInt": "18",
    "baseStr": "19",
    "bonusAgi": "1.3",
    "bonusInt": "2",
    "name": "Tojara",
    "story": "",
    "bonusStr": "2.3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNChaosBlademaster.blp",
    "attackRate": "1.6",
    "attackRange": "100"
  },
  {
    "type": "Shadow Hunter",
    "id": "Oshd",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "18",
    "armor": "2",
    "life": "175",
    "regenLife": "0.9",
    "mana": "110",
    "regenMana": "1.3",
    "moveSpeed": "305",
    "baseAgi": "20",
    "baseInt": "20",
    "baseStr": "15",
    "bonusAgi": "1.8",
    "bonusInt": "2.6",
    "name": "Rokhan",
    "story": "",
    "bonusStr": "1.9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNShadowHunter.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Death Knight",
    "id": "Udea",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "22",
    "armor": "3",
    "life": "210",
    "regenLife": "1.9",
    "mana": "80",
    "regenMana": "0.95",
    "moveSpeed": "310",
    "baseAgi": "13",
    "baseInt": "17",
    "baseStr": "24",
    "bonusAgi": "1.6",
    "bonusInt": "1.7",
    "name": "Baron Bloodbane",
    "story": "",
    "bonusStr": "2.7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroDeathKnight.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Lich",
    "id": "Ulic",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "17",
    "armor": "2",
    "life": "190",
    "regenLife": "1.1",
    "mana": "140",
    "regenMana": "1.2",
    "moveSpeed": "295",
    "baseAgi": "15",
    "baseInt": "22",
    "baseStr": "16",
    "bonusAgi": "1.3",
    "bonusInt": "3.4",
    "name": "Kel'thuzad",
    "story": "",
    "bonusStr": "1.9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNLichVersion2.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Dreadlord",
    "id": "Udre",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "12",
    "armor": "4",
    "life": "185",
    "regenLife": "2",
    "mana": "100",
    "regenMana": "1",
    "moveSpeed": "300",
    "baseAgi": "18",
    "baseInt": "15",
    "baseStr": "20",
    "bonusAgi": "2",
    "bonusInt": "1.5",
    "name": "Tichondrius",
    "story": "",
    "bonusStr": "2.6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNTichondrius.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Crypt Lord",
    "id": "Ucrl",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "20",
    "armor": "5",
    "life": "190",
    "regenLife": "2.2",
    "mana": "110",
    "regenMana": "1.1",
    "moveSpeed": "285",
    "baseAgi": "14",
    "baseInt": "14",
    "baseStr": "26",
    "bonusAgi": "1.2",
    "bonusInt": "1.6",
    "name": "Anub'arak",
    "story": "",
    "bonusStr": "3.2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroCryptLord.blp",
    "attackRate": "1.7",
    "attackRange": "128"
  },
  {
    "type": "Eredar",
    "id": "Uwar",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "25",
    "armor": "3",
    "life": "170",
    "regenLife": "1.2",
    "mana": "120",
    "regenMana": "1.2",
    "moveSpeed": "310",
    "baseAgi": "18",
    "baseInt": "20",
    "baseStr": "18",
    "bonusAgi": "2.2",
    "bonusInt": "2.5",
    "name": "Archimonde",
    "story": "",
    "bonusStr": "1.8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNArchimonde.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Alchemist",
    "id": "Nalc",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "15",
    "armor": "1",
    "life": "210",
    "regenLife": "2.3",
    "mana": "115",
    "regenMana": "1",
    "moveSpeed": "310",
    "baseAgi": "9",
    "baseInt": "18",
    "baseStr": "24",
    "bonusAgi": "1.1",
    "bonusInt": "2",
    "name": "Ezzel Darkbrewer",
    "story": "",
    "bonusStr": "3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroAlchemist.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Naga Sea Witch",
    "id": "Nngs",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "10",
    "armor": "2",
    "life": "195",
    "regenLife": "1.9",
    "mana": "120",
    "regenMana": "1.2",
    "moveSpeed": "310",
    "baseAgi": "17",
    "baseInt": "20",
    "baseStr": "15",
    "bonusAgi": "2.4",
    "bonusInt": "3",
    "name": "Lady Vashj",
    "story": "",
    "bonusStr": "1.7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNNagaSeaWitch.blp",
    "attackRate": "1.6",
    "attackRange": "600"
  },
  {
    "type": "Tinker",
    "id": "Ntin",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "19",
    "armor": "3",
    "life": "120",
    "regenLife": "1.1",
    "mana": "130",
    "regenMana": "1.4",
    "moveSpeed": "295",
    "baseAgi": "15",
    "baseInt": "21",
    "baseStr": "20",
    "bonusAgi": "1.5",
    "bonusInt": "3",
    "name": "Mekka Gobb",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroTinker.blp",
    "attackRate": "1.65",
    "attackRange": "600"
  },
  {
    "type": "Warlock",
    "id": "Nklj",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "25",
    "armor": "3",
    "life": "200",
    "regenLife": "2.1",
    "mana": "100",
    "regenMana": "0.7",
    "moveSpeed": "300",
    "baseAgi": "16",
    "baseInt": "17",
    "baseStr": "24",
    "bonusAgi": "1.9",
    "bonusInt": "1.5",
    "name": "Kil'jaeden",
    "story": "",
    "bonusStr": "3.5",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNKiljaedin.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Admiral",
    "id": "Hapm",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "22",
    "armor": "2",
    "life": "190",
    "regenLife": "2",
    "mana": "100",
    "regenMana": "0.95",
    "moveSpeed": "290",
    "baseAgi": "20",
    "baseInt": "14",
    "baseStr": "22",
    "bonusAgi": "2.2",
    "bonusInt": "1.5",
    "name": "Daelin Proudmoore",
    "story": "",
    "bonusStr": "2.8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNProudmoore.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Ancient Apparition",
    "id": "Ekgg",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "23",
    "armor": "2",
    "life": "180",
    "regenLife": "1",
    "mana": "125",
    "regenMana": "1",
    "moveSpeed": "310",
    "baseAgi": "15",
    "baseInt": "24",
    "baseStr": "18",
    "bonusAgi": "1.5",
    "bonusInt": "3.1",
    "name": "Lord Maldazzar",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNKeeperGhostBlue.blp",
    "attackRate": "1.6",
    "attackRange": "600"
  },
  {
    "type": "Beastmaster",
    "id": "Nbst",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "24",
    "armor": "5",
    "life": "210",
    "regenLife": "2.4",
    "mana": "85",
    "regenMana": "1.25",
    "moveSpeed": "315",
    "baseAgi": "18",
    "baseInt": "15",
    "baseStr": "25",
    "bonusAgi": "2.2",
    "bonusInt": "1.4",
    "name": "Rexxar",
    "story": "",
    "bonusStr": "2.9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNBeastMaster.blp",
    "attackRate": "1.6",
    "attackRange": "128"
  },
  {
    "type": "Betrayer",
    "id": "Eevi",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "21",
    "armor": "6",
    "life": "180",
    "regenLife": "1.4",
    "mana": "95",
    "regenMana": "1.15",
    "moveSpeed": "320",
    "baseAgi": "27",
    "baseInt": "16",
    "baseStr": "15",
    "bonusAgi": "3.3",
    "bonusInt": "1.7",
    "name": "Illidan",
    "story": "",
    "bonusStr": "1.3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNEvilIllidan.blp",
    "attackRate": "1.5",
    "attackRange": "100"
  },
  {
    "type": "Dark Knight",
    "id": "Hlgr",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "28",
    "armor": "4",
    "life": "220",
    "regenLife": "1.5",
    "mana": "90",
    "regenMana": "1.05",
    "moveSpeed": "300",
    "baseAgi": "13",
    "baseInt": "14",
    "baseStr": "28",
    "bonusAgi": "1.2",
    "bonusInt": "1.3",
    "name": "Lord Garithos",
    "story": "",
    "bonusStr": "4.5",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNGarithos.blp",
    "attackRate": "1.7",
    "attackRange": "100"
  },
  {
    "type": "Dark Ranger",
    "id": "Nbrn",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "23",
    "armor": "1",
    "life": "150",
    "regenLife": "0.9",
    "mana": "85",
    "regenMana": "1",
    "moveSpeed": "315",
    "baseAgi": "22",
    "baseInt": "16",
    "baseStr": "16",
    "bonusAgi": "2.4",
    "bonusInt": "2",
    "name": "Sylvanas",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNBansheeRanger.blp",
    "attackRate": "1.65",
    "attackRange": "600"
  },
  {
    "type": "Fierce Knight",
    "id": "Harf",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "22",
    "armor": "4",
    "life": "210",
    "regenLife": "2.5",
    "mana": "90",
    "regenMana": "1.1",
    "moveSpeed": "290",
    "baseAgi": "14",
    "baseInt": "17",
    "baseStr": "23",
    "bonusAgi": "1.7",
    "bonusInt": "1.8",
    "name": "Aurrius the Pure",
    "story": "",
    "bonusStr": "2.8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNArthas.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Firelord",
    "id": "Nfir",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "30",
    "armor": "2",
    "life": "130",
    "regenLife": "0.90",
    "mana": "110",
    "regenMana": "1.2",
    "moveSpeed": "320",
    "baseAgi": "22",
    "baseInt": "20",
    "baseStr": "14",
    "bonusAgi": "2.1",
    "bonusInt": "2",
    "name": "Ragnaros",
    "story": "",
    "bonusStr": "1.8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroAvatarOfFlame.blp",
    "attackRate": "1.65",
    "attackRange": "550"
  },
  {
    "type": "Holy Apparition",
    "id": "Hgam",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "17",
    "armor": "0",
    "life": "150",
    "regenLife": "1.05",
    "mana": "130",
    "regenMana": "1.4",
    "moveSpeed": "330",
    "baseAgi": "17",
    "baseInt": "25",
    "baseStr": "14",
    "bonusAgi": "1.4",
    "bonusInt": "3.2",
    "name": "Antonidas",
    "story": "",
    "bonusStr": "1.6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNGhostMage.blp",
    "attackRate": "1.6",
    "attackRange": "600"
  },
  {
    "type": "Maiden",
    "id": "Hjai",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "23",
    "armor": "1",
    "life": "140",
    "regenLife": "0.95",
    "mana": "130",
    "regenMana": "1.6",
    "moveSpeed": "290",
    "baseAgi": "17",
    "baseInt": "20",
    "baseStr": "16",
    "bonusAgi": "1.3",
    "bonusInt": "3.2",
    "name": "Jaina",
    "story": "",
    "bonusStr": "1.7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNJaina.blp",
    "attackRate": "1.7",
    "attackRange": "600"
  },
  {
    "type": "Pandaren Brewmaster",
    "id": "Npbm",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "28",
    "armor": "3",
    "life": "190",
    "regenLife": "2",
    "mana": "85",
    "regenMana": "1.2",
    "moveSpeed": "295",
    "baseAgi": "14",
    "baseInt": "18",
    "baseStr": "22",
    "bonusAgi": "1.6",
    "bonusInt": "1.7",
    "name": "Mojo Barrel-keg",
    "story": "",
    "bonusStr": "2.9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNPandarenBrewmaster.blp",
    "attackRate": "1.6",
    "attackRange": "100"
  },
  {
    "type": "Pit Lord",
    "id": "Nplh",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "25",
    "armor": "3",
    "life": "220",
    "regenLife": "2.4",
    "mana": "100",
    "regenMana": "0.8",
    "moveSpeed": "290",
    "baseAgi": "14",
    "baseInt": "15",
    "baseStr": "24",
    "bonusAgi": "1.4",
    "bonusInt": "1.6",
    "name": "Magtheridon",
    "story": "",
    "bonusStr": "3.2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNPitLord.blp",
    "attackRate": "1.7",
    "attackRange": "100"
  },
  {
    "type": "Prophet",
    "id": "Emfr",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "19",
    "armor": "2",
    "life": "160",
    "regenLife": "1.6",
    "mana": "110",
    "regenMana": "1.1",
    "moveSpeed": "310",
    "baseAgi": "18",
    "baseInt": "22",
    "baseStr": "16",
    "bonusAgi": "2",
    "bonusInt": "2.9",
    "name": "Malfurion",
    "story": "",
    "bonusStr": "1.7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNFurion.blp",
    "attackRate": "1.65",
    "attackRange": "600"
  },
  {
    "type": "Rampager",
    "id": "Opgh",
    "typeAttk": "Ranged",
    "mainAttribute": "Strength",
    "damages": "18",
    "armor": "4",
    "life": "215",
    "regenLife": "2.8",
    "mana": "80",
    "regenMana": "0.8",
    "moveSpeed": "310",
    "baseAgi": "20",
    "baseInt": "16",
    "baseStr": "23",
    "bonusAgi": "2",
    "bonusInt": "1.7",
    "name": "Grom Hellscream",
    "story": "",
    "bonusStr": "2.6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNChaosGrom.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "type": "Ranger",
    "id": "Hvwd",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "26",
    "armor": "2",
    "life": "170",
    "regenLife": "1.2",
    "mana": "110",
    "regenMana": "1.3",
    "moveSpeed": "310",
    "baseAgi": "21",
    "baseInt": "15",
    "baseStr": "19",
    "bonusAgi": "2.5",
    "bonusInt": "2.1",
    "name": "Kathris Whisperwind",
    "story": "",
    "bonusStr": "1.9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNSylvanusWindrunner.blp",
    "attackRate": "1.65",
    "attackRange": "600"
  },
  {
    "type": "Fel Lord",
    "id": "O00F",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "15",
    "armor": "0",
    "life": "230",
    "regenLife": "2.2",
    "mana": "90",
    "regenMana": "1",
    "moveSpeed": "285",
    "baseAgi": "15",
    "baseInt": "11",
    "baseStr": "25",
    "bonusAgi": "1.8",
    "bonusInt": "1.2",
    "name": "Tygore Harpyslayer",
    "story": "",
    "bonusStr": "3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNFelGuardBlue.blp",
    "attackRate": "1.7",
    "attackRange": "128"
  },
  {
    "type": "Spirit Walker",
    "id": "O00H",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "16",
    "armor": "3",
    "life": "220",
    "regenLife": "2.5",
    "mana": "110",
    "regenMana": "1.05",
    "moveSpeed": "290",
    "baseAgi": "20",
    "baseInt": "10",
    "baseStr": "24",
    "bonusAgi": "2.5",
    "bonusInt": "2.3",
    "name": "Marn Runetotem",
    "story": "",
    "bonusStr": "2.6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNSpiritWalker.blp",
    "attackRate": "1.65",
    "attackRange": "128"
  },
  {
    "type": "Draenei Assassin",
    "id": "Naka",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "25",
    "armor": "2",
    "life": "180",
    "regenLife": "1.9",
    "mana": "70",
    "regenMana": "0.8",
    "moveSpeed": "305",
    "baseAgi": "22",
    "baseInt": "18",
    "baseStr": "19",
    "bonusAgi": "3.5",
    "bonusInt": "2",
    "name": "Akama",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNDranaiAkama.blp",
    "attackRate": "1.5",
    "attackRange": "90"
  },
  {
    "type": "Tiggerian Slicer",
    "id": "E003",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "18",
    "armor": "2",
    "life": "170",
    "regenLife": "1.4",
    "mana": "70",
    "regenMana": "1",
    "moveSpeed": "305",
    "baseAgi": "24",
    "baseInt": "16",
    "baseStr": "19",
    "bonusAgi": "2.8",
    "bonusInt": "1.9",
    "name": "Terrorblade",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNPriestessOfTheMoon.blp",
    "attackRate": "1.45",
    "attackRange": "100"
  },
  {
    "type": "Judgment Clerc",
    "id": "H039",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "10",
    "armor": "4",
    "life": "190",
    "regenLife": "2.1",
    "mana": "115",
    "regenMana": "1",
    "moveSpeed": "285",
    "baseAgi": "14",
    "baseInt": "18",
    "baseStr": "22",
    "bonusAgi": "1.5",
    "bonusInt": "1.9",
    "name": "Ballador Darkhammer",
    "story": "",
    "bonusStr": "2.7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTN_JudgmentClerc.blp",
    "attackRate": "1.65",
    "attackRange": "100"
  },
  {
    "id": "H08L",
    "type": "Gryphon Lord",
    "name": "Zann the Defender",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNGryphonRider.blp",
    "mainAttribute": "Strength",
    "baseAgi": "15",
    "baseInt": "16",
    "baseStr": "21",
    "bonusAgi": "1.6",
    "bonusInt": "1.9",
    "bonusStr": "2.4",
    "moveSpeed": "290",
    "typeAttk": "Melee",
    "damages": "15",
    "attackRate": "1.7",
    "attackRange": "100",
    "armor": "3",
    "life": "175",
    "regenLife": "2",
    "mana": "105",
    "regenMana": "1.1"
  },
  {
    "type": "Titan Hyperion",
    "id": "O00O",
    "name": "Diablo",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNDiabloCar.blp",
    "mainAttribute": "Strength",
    "baseAgi": "18",
    "baseInt": "16",
    "baseStr": "28",
    "bonusAgi": "1.1",
    "bonusInt": "1.4",
    "bonusStr": "3.5",
    "moveSpeed": "280",
    "typeAttk": "Melee",
    "damages": "31",
    "attackRate": "1.7",
    "attackRange": "128",
    "armor": "3",
    "life": "225",
    "regenLife": "3",
    "mana": "90",
    "regenMana": "0.9"
  },
  {
    "id": "E005",
    "type": "Werewolf",
    "name": "Anat'ir",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNTimberWolf.blp",
    "mainAttribute": "Agility",
    "baseAgi": "23",
    "baseInt": "18",
    "baseStr": "18",
    "bonusAgi": "3",
    "bonusInt": "1.6",
    "bonusStr": "1.9",
    "moveSpeed": "310",
    "typeAttk": "Melee",
    "damages": "35",
    "attackRate": "1.65",
    "attackRange": "100",
    "armor": "2",
    "life": "170",
    "regenLife": "1.5",
    "mana": "100",
    "regenMana": "1"
  }
]