const defaultHeroes = [
  {
    "type": "Keeper of the Grove",
    "id": "Ekee",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "22",
    "armor": "1",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "320",
    "baseAgi": "19",
    "baseInt": "24",
    "baseStr": "18",
    "bonusAgi": "1,8",
    "bonusInt": "2,8",
    "name": "Cenarius",
    "story": "",
    "bonusStr": "1,9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNKeeperOfTheGrove.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Priestess of the Moon",
    "id": "Emoo",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "12",
    "armor": "1",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "22",
    "baseInt": "16",
    "baseStr": "16",
    "bonusAgi": "2,4",
    "bonusInt": "2,6",
    "name": "Tyrande",
    "story": "",
    "bonusStr": "1,5",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNShandris.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Demon Hunter",
    "id": "Edem",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "18",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "305",
    "baseAgi": "24",
    "baseInt": "16",
    "baseStr": "19",
    "bonusAgi": "2,8",
    "bonusInt": "1,9",
    "name": "Shadowfury",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroDemonHunter.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Warden",
    "id": "Ewar",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "25",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "295",
    "baseAgi": "22",
    "baseInt": "15",
    "baseStr": "20",
    "bonusAgi": "2,4",
    "bonusInt": "1,8",
    "name": "Maiev",
    "story": "",
    "bonusStr": "2,2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroWarden.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Paladin",
    "id": "Hpal",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "10",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "285",
    "baseAgi": "14",
    "baseInt": "18",
    "baseStr": "22",
    "bonusAgi": "1,5",
    "bonusInt": "1,9",
    "name": "Uther",
    "story": "",
    "bonusStr": "2,7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Archmage",
    "id": "Hamg",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "16",
    "armor": "1",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "315",
    "baseAgi": "17",
    "baseInt": "19",
    "baseStr": "14",
    "bonusAgi": "1",
    "bonusInt": "3,2",
    "name": "Andromath",
    "story": "",
    "bonusStr": "1,8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroArchMage.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Mountain King",
    "id": "Hmkg",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "15",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "290",
    "baseAgi": "12",
    "baseInt": "15",
    "baseStr": "24",
    "bonusAgi": "1,5",
    "bonusInt": "1,5",
    "name": "Kaz Modan",
    "story": "",
    "bonusStr": "3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroMountainKing.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Blood Mage",
    "id": "Hblm",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "25",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "290",
    "baseAgi": "16",
    "baseInt": "20",
    "baseStr": "18",
    "bonusAgi": "1,2",
    "bonusInt": "3",
    "name": "Kael",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroBloodElfPrince.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Blademaster",
    "id": "Obla",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "30",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "305",
    "baseAgi": "24",
    "baseInt": "16",
    "baseStr": "19",
    "bonusAgi": "3,1",
    "bonusInt": "2",
    "name": "Samuro",
    "story": "",
    "bonusStr": "2,2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroBlademaster.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Far Seer",
    "id": "Ofar",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "12",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "19",
    "baseInt": "23",
    "baseStr": "15",
    "bonusAgi": "1,3",
    "bonusInt": "2,9",
    "name": "Thrall",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroFarseer.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Tauren Chieftain",
    "id": "Otch",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "20",
    "armor": "0",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "285",
    "baseAgi": "10",
    "baseInt": "14",
    "baseStr": "25",
    "bonusAgi": "1,5",
    "bonusInt": "1,3",
    "name": "Cairne Dusthoof",
    "story": "",
    "bonusStr": "3,2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroTaurenChieftain.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Juggernault",
    "id": "Nbbc",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "15",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "23",
    "baseInt": "18",
    "baseStr": "19",
    "bonusAgi": "1,3",
    "bonusInt": "2",
    "name": "Tojara",
    "story": "",
    "bonusStr": "2,3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNChaosBlademaster.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Shadow Hunter",
    "id": "Oshd",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "18",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "305",
    "baseAgi": "20",
    "baseInt": "20",
    "baseStr": "15",
    "bonusAgi": "1,8",
    "bonusInt": "2,6",
    "name": "Rokhan",
    "story": "",
    "bonusStr": "1,9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNShadowHunter.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Death Knight",
    "id": "Udea",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "22",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "13",
    "baseInt": "17",
    "baseStr": "24",
    "bonusAgi": "1,6",
    "bonusInt": "1,7",
    "name": "Baron Bloodbane",
    "story": "",
    "bonusStr": "2,7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroDeathKnight.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Lich",
    "id": "Ulic",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "17",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "295",
    "baseAgi": "15",
    "baseInt": "22",
    "baseStr": "16",
    "bonusAgi": "1,3",
    "bonusInt": "3,4",
    "name": "Kel'thuzad",
    "story": "",
    "bonusStr": "1,9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNLichVersion2.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Dreadlord",
    "id": "Udre",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "12",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "300",
    "baseAgi": "18",
    "baseInt": "15",
    "baseStr": "20",
    "bonusAgi": "2",
    "bonusInt": "1,5",
    "name": "Tichondrius",
    "story": "",
    "bonusStr": "2,6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNTichondrius.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Crypt Lord",
    "id": "Ucrl",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "20",
    "armor": "5",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "285",
    "baseAgi": "14",
    "baseInt": "14",
    "baseStr": "26",
    "bonusAgi": "1,2",
    "bonusInt": "1,6",
    "name": "Anub'arak",
    "story": "",
    "bonusStr": "3,2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroCryptLord.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Eredar",
    "id": "Uwar",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "25",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "18",
    "baseInt": "20",
    "baseStr": "18",
    "bonusAgi": "2,5",
    "bonusInt": "2,5",
    "name": "Archimonde",
    "story": "",
    "bonusStr": "1,8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNArchimonde.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Alchemist",
    "id": "Nalc",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "15",
    "armor": "1",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "9",
    "baseInt": "18",
    "baseStr": "24",
    "bonusAgi": "1,1",
    "bonusInt": "2",
    "name": "Ezzel Darkbrewer",
    "story": "",
    "bonusStr": "3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroAlchemist.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Naga Sea Witch",
    "id": "Nngs",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "10",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "17",
    "baseInt": "20",
    "baseStr": "15",
    "bonusAgi": "2,4",
    "bonusInt": "3",
    "name": "Lady Vashj",
    "story": "",
    "bonusStr": "1,7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNNagaSeaWitch.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Tinker",
    "id": "Ntin",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "19",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "295",
    "baseAgi": "15",
    "baseInt": "21",
    "baseStr": "20",
    "bonusAgi": "1,5",
    "bonusInt": "3",
    "name": "Mekka Gobb",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroTinker.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Warlock",
    "id": "Nklj",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "25",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "300",
    "baseAgi": "16",
    "baseInt": "17",
    "baseStr": "24",
    "bonusAgi": "1,9",
    "bonusInt": "1,5",
    "name": "Kil'jaeden",
    "story": "",
    "bonusStr": "3,5",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNKiljaedin.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Admiral",
    "id": "Hapm",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "22",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "290",
    "baseAgi": "20",
    "baseInt": "14",
    "baseStr": "22",
    "bonusAgi": "2,2",
    "bonusInt": "1,5",
    "name": "Daelin Proudmoore",
    "story": "",
    "bonusStr": "2,8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNProudmoore.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Ancient Apparition",
    "id": "Ekgg",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "23",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "15",
    "baseInt": "24",
    "baseStr": "18",
    "bonusAgi": "1,5",
    "bonusInt": "3,1",
    "name": "Lord Maldazzar",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNKeeperGhostBlue.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Beastmaster",
    "id": "Nbst",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "24",
    "armor": "5",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "315",
    "baseAgi": "18",
    "baseInt": "15",
    "baseStr": "25",
    "bonusAgi": "2,2",
    "bonusInt": "1,4",
    "name": "Rexxar",
    "story": "",
    "bonusStr": "2,9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNBeastMaster.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Betrayer",
    "id": "Eevi",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "21",
    "armor": "6",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "320",
    "baseAgi": "27",
    "baseInt": "16",
    "baseStr": "15",
    "bonusAgi": "3,3",
    "bonusInt": "1,7",
    "name": "Illidan",
    "story": "",
    "bonusStr": "1,3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNEvilIllidan.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Dark Knight",
    "id": "Hlgr",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "28",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "300",
    "baseAgi": "13",
    "baseInt": "14",
    "baseStr": "28",
    "bonusAgi": "1,2",
    "bonusInt": "1,3",
    "name": "Lord Garithos",
    "story": "",
    "bonusStr": "4,5",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNGarithos.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Dark Ranger",
    "id": "Nbrn",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "23",
    "armor": "1",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "315",
    "baseAgi": "22",
    "baseInt": "16",
    "baseStr": "16",
    "bonusAgi": "2,4",
    "bonusInt": "2",
    "name": "Sylvanas",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNBansheeRanger.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Fierce Knight",
    "id": "Harf",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "22",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "290",
    "baseAgi": "14",
    "baseInt": "17",
    "baseStr": "23",
    "bonusAgi": "1,7",
    "bonusInt": "1,8",
    "name": "Aurrius the Pure",
    "story": "",
    "bonusStr": "2,8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNArthas.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Firelord",
    "id": "Nfir",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "30",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "320",
    "baseAgi": "22",
    "baseInt": "20",
    "baseStr": "14",
    "bonusAgi": "2,1",
    "bonusInt": "2",
    "name": "Ragnaros",
    "story": "",
    "bonusStr": "1,8",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNHeroAvatarOfFlame.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Holy Apparition",
    "id": "Hgam",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "17",
    "armor": "0",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "330",
    "baseAgi": "17",
    "baseInt": "25",
    "baseStr": "14",
    "bonusAgi": "1,4",
    "bonusInt": "3,2",
    "name": "Antonidas",
    "story": "",
    "bonusStr": "1,6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNGhostMage.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Maiden",
    "id": "Hjai",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "23",
    "armor": "1",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "290",
    "baseAgi": "17",
    "baseInt": "20",
    "baseStr": "16",
    "bonusAgi": "1,3",
    "bonusInt": "3,2",
    "name": "Jaina",
    "story": "",
    "bonusStr": "1,7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNJaina.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Pandaren Brewmaster",
    "id": "Npbm",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "28",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "295",
    "baseAgi": "14",
    "baseInt": "18",
    "baseStr": "22",
    "bonusAgi": "1,6",
    "bonusInt": "1,7",
    "name": "Mojo Barrel-keg",
    "story": "",
    "bonusStr": "2,9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNPandarenBrewmaster.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Pit Lord",
    "id": "Nplh",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "25",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "290",
    "baseAgi": "14",
    "baseInt": "15",
    "baseStr": "24",
    "bonusAgi": "1,4",
    "bonusInt": "1,6",
    "name": "Magtheridon",
    "story": "",
    "bonusStr": "3,2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNPitLord.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Prophet",
    "id": "Emfr",
    "typeAttk": "Ranged",
    "mainAttribute": "Intelligence",
    "damages": "19",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "18",
    "baseInt": "22",
    "baseStr": "16",
    "bonusAgi": "2",
    "bonusInt": "2,9",
    "name": "Malfurion",
    "story": "",
    "bonusStr": "1,7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNFurion.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Rampager",
    "id": "Opgh",
    "typeAttk": "Ranged",
    "mainAttribute": "Strength",
    "damages": "18",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "20",
    "baseInt": "16",
    "baseStr": "23",
    "bonusAgi": "2",
    "bonusInt": "1,7",
    "name": "Grom Hellscream",
    "story": "",
    "bonusStr": "2,6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNChaosGrom.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Ranger",
    "id": "Hvwd",
    "typeAttk": "Ranged",
    "mainAttribute": "Agility",
    "damages": "26",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "310",
    "baseAgi": "21",
    "baseInt": "15",
    "baseStr": "19",
    "bonusAgi": "2,5",
    "bonusInt": "2,1",
    "name": "Kathris Whisperwind",
    "story": "",
    "bonusStr": "1,9",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNSylvanusWindrunner.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Fel Lord",
    "id": "O00F",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "15",
    "armor": "0",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "285",
    "baseAgi": "15",
    "baseInt": "11",
    "baseStr": "25",
    "bonusAgi": "1,8",
    "bonusInt": "1,2",
    "name": "Tygore Harpyslayer",
    "story": "",
    "bonusStr": "3",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNFelGuardBlue.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Spirit Walker",
    "id": "O00H",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "16",
    "armor": "3",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "1,01",
    "moveSpeed": "290",
    "baseAgi": "20",
    "baseInt": "10",
    "baseStr": "24",
    "bonusAgi": "2,5",
    "bonusInt": "2,3",
    "name": "Marn Runetotem",
    "story": "",
    "bonusStr": "2,6",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNSpiritWalker.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Draenei Assassin",
    "id": "Naka",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "25",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "2,01",
    "moveSpeed": "305",
    "baseAgi": "22",
    "baseInt": "18",
    "baseStr": "19",
    "bonusAgi": "3,5",
    "bonusInt": "2",
    "name": "Akama",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNDranaiAkama.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Tiggerian Slicer",
    "id": "E003",
    "typeAttk": "Melee",
    "mainAttribute": "Agility",
    "damages": "18",
    "armor": "2",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "305",
    "baseAgi": "24",
    "baseInt": "16",
    "baseStr": "19",
    "bonusAgi": "2,8",
    "bonusInt": "1,9",
    "name": "Terrorblade",
    "story": "",
    "bonusStr": "2",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTNPriestessOfTheMoon.blp",
    "attackRate": "1.7"
  },
  {
    "type": "Judgment Clerc",
    "id": "H039",
    "typeAttk": "Melee",
    "mainAttribute": "Strength",
    "damages": "10",
    "armor": "4",
    "life": "100",
    "regenLife": "0,5",
    "mana": "100",
    "regenMana": "0,01",
    "moveSpeed": "285",
    "baseAgi": "14",
    "baseInt": "18",
    "baseStr": "22",
    "bonusAgi": "1,5",
    "bonusInt": "1,9",
    "name": "Ballador Darkhammer",
    "story": "",
    "bonusStr": "2,7",
    "iconPath": "ReplaceableTextures\\CommandButtons\\BTN_JudgmentClerc.blp",
    "attackRate": "1.7"
  }
]